<?php include __DIR__ . '/../../includes/header.php'; require_permission('accesos.ver');
$areas=$pdo->query("SELECT * FROM areas_restringidas ORDER BY nombre_area")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action'];
 if($action==='qr'){ $qr=trim($_POST['qr']); $st=$pdo->prepare("SELECT * FROM visitantes WHERE qr_generado=? LIMIT 1");$st->execute([$qr]);$v=$st->fetch();
  if($v && $v['estado_autorizacion']==='APROBADO'){ $pdo->prepare("INSERT INTO accesos(tipo_persona,id_referencia,id_area,estado_acceso,metodo_validacion) VALUES('VISITANTE',?,?, 'PERMITIDO','QR')")->execute([$v['id_visitante'],$_POST['id_area'] ?: null]); log_event('ACCESO_PERMITIDO_QR',"Visitante ".$v['nombres']); flash('success','Acceso permitido y registrado.');}
  else { $pdo->prepare("INSERT INTO accesos(tipo_persona,id_referencia,id_area,estado_acceso,metodo_validacion) VALUES('VISITANTE',0,?, 'DENEGADO','QR')")->execute([$_POST['id_area'] ?: null]); $idAcc=$pdo->lastInsertId(); $pdo->prepare("INSERT INTO alertas(id_acceso,tipo_alerta,descripcion,severidad) VALUES(?,?,?,?)")->execute([$idAcc,'QR inválido','Intento de acceso con QR inválido o visitante no aprobado','ALTA']); log_event('ACCESO_DENEGADO_QR','QR inválido'); flash('danger','Acceso denegado. Se generó alerta.');}
 }
 if($action==='manual'){ $pdo->prepare("INSERT INTO accesos(tipo_persona,id_referencia,id_area,estado_acceso,metodo_validacion) VALUES(?,?,?,?, 'MANUAL')")->execute([$_POST['tipo_persona'],$_POST['id_referencia'],$_POST['id_area'] ?: null,$_POST['estado_acceso']]); log_event('ACCESO_MANUAL','Registro manual de acceso'); flash('success','Acceso manual registrado.');}
 if($action==='salida'){ $pdo->prepare("UPDATE accesos SET fecha_hora_salida=NOW() WHERE id_acceso=?")->execute([$_POST['id_acceso']]); log_event('REGISTRAR_SALIDA',"Acceso ID ".$_POST['id_acceso']); flash('success','Salida registrada.');}
 redirect('index.php');
}
$rows=$pdo->query("SELECT * FROM v_accesos_detalle ORDER BY fecha_hora_ingreso DESC LIMIT 100")->fetchAll();
?>
<h1>Control de accesos</h1><div class="two-col"><div class="card"><h2>Validar QR</h2><form method="POST"><input type="hidden" name="action" value="qr"><label>Código QR</label><input name="qr" required><label>Área</label><select name="id_area"><option value="">General</option><?php foreach($areas as $a): ?><option value="<?= $a['id_area'] ?>"><?= e($a['nombre_area']) ?></option><?php endforeach; ?></select><br><br><button>Validar acceso</button></form></div><div class="card"><h2>Registro manual</h2><form method="POST"><input type="hidden" name="action" value="manual"><label>Tipo persona</label><select name="tipo_persona"><option>USUARIO</option><option>VISITANTE</option></select><label>ID referencia</label><input name="id_referencia" required><label>Área</label><select name="id_area"><option value="">General</option><?php foreach($areas as $a): ?><option value="<?= $a['id_area'] ?>"><?= e($a['nombre_area']) ?></option><?php endforeach; ?></select><label>Estado</label><select name="estado_acceso"><option>PERMITIDO</option><option>DENEGADO</option></select><br><br><button>Registrar</button></form></div></div>
<div class="card"><h2>Historial de accesos</h2><table><tr><th>ID</th><th>Persona</th><th>Tipo</th><th>Área</th><th>Ingreso</th><th>Salida</th><th>Estado</th><th>Acción</th></tr><?php foreach($rows as $r): ?><tr><td><?= $r['id_acceso'] ?></td><td><?= e($r['persona']) ?></td><td><?= e($r['tipo_persona']) ?></td><td><?= e($r['area']??'General') ?></td><td><?= e($r['fecha_hora_ingreso']) ?></td><td><?= e($r['fecha_hora_salida']??'Dentro') ?></td><td><?= e($r['estado_acceso']) ?></td><td><?php if(!$r['fecha_hora_salida'] && $r['estado_acceso']=='PERMITIDO'): ?><form method="POST"><input type="hidden" name="action" value="salida"><input type="hidden" name="id_acceso" value="<?= $r['id_acceso'] ?>"><button class="btn btn-warning">Registrar salida</button></form><?php endif; ?></td></tr><?php endforeach; ?></table></div><?php include __DIR__ . '/../../includes/footer.php'; ?>
